# Generated by Django 2.0.5 on 2018-08-21 06:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_expired', models.DateField(default=datetime.datetime(2018, 8, 21, 6, 30, 12, 145738, tzinfo=utc))),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_expired'],
            },
        ),
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='GenericExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_expired', models.DateField(default=datetime.datetime(2018, 8, 21, 6, 30, 12, 145738, tzinfo=utc))),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentMethod')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Απασχόληση')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Υπόλοιπο')),
            ],
            options={
                'verbose_name_plural': '5. Απασχόληση',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Περιγραφή')),
                ('category', models.CharField(choices=[('1', 'Μισθός'), ('2', 'ΙΚΑ'), ('3', 'ΑΣΦΑΛΙΣΤΙΚΕΣ ΕΙΣΦΟΡΕΣ'), ('4', 'ΗΜΕΡΟΜΗΣΘΙΟ'), ('5', 'ΕΡΓΟΣΗΜΟ'), ('6', 'ΔΩΡΟ')], default='1', max_length=1)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Αξία')),
                ('date_created', models.DateField(auto_now=True)),
                ('date_expired', models.DateField(default=django.utils.timezone.now, verbose_name='Πληρωμή μέχρι .....')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Πιστωτικό Υπόλοιπο')),
                ('payment_method', models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], default='1', max_length=1)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '7. Εντολές Πληρωμής Υπαλλήλων. ',
                'ordering': ['is_paid', '-date_expired'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Ονοματεπώνυμο')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο')),
                ('phone1', models.CharField(blank=True, max_length=10, verbose_name='Κινητό')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Πρόσληψης')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Υπόλοιπο')),
                ('vacation_days', models.IntegerField(default=0)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Occupation', verbose_name='Απασχόληση')),
                ('store_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_settings.Store')),
            ],
            options={
                'verbose_name_plural': '6. Υπάλληλος',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Ολοκληρώθηκε')),
                ('date_started', models.DateField()),
                ('date_end', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['status', 'date_started', 'date_end'],
            },
        ),
        migrations.CreateModel(
            name='VacationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacation',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcations.VacationReason'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='staff_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='transcations.Person'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcations.BillCategory'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
