# Generated by Django 2.0 on 2018-08-21 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['is_paid', '-date_expired']},
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='active',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='date_created',
        ),
        migrations.AddField(
            model_name='payroll',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 21, 12, 18, 23, 334898, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 21, 12, 17, 42, 956739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 21, 12, 17, 42, 956739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 21, 12, 17, 42, 956739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='title',
            field=models.CharField(default='de', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
