# Generated by Django 2.0.5 on 2018-12-02 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20181202_1845'),
        ('transcations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date_expired'], 'verbose_name': 'Λογαριασμός', 'verbose_name_plural': '1. Εντολη Πληρωμης Λογαριασμού'},
        ),
        migrations.AlterModelOptions(
            name='billcategory',
            options={'verbose_name_plural': '4. Λογαριασμοί'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Απασχόληση', 'verbose_name_plural': '4. Απασχόληση'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Υπάλληλος', 'verbose_name_plural': '6. Υπάλληλος'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='store_related',
            new_name='store',
        ),
        migrations.AddField(
            model_name='billcategory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Store'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_expired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='date_expired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date_expired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
