# Generated by Django 2.0 on 2018-08-22 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0002_auto_20180821_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcations.GenericExpenseCategory'),
        ),
        migrations.AddField(
            model_name='genericexpensecategory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='genericexpensecategory',
            name='title',
            field=models.CharField(default='p', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='transcations.BillCategory'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 22, 9, 20, 36, 607111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 22, 9, 20, 36, 607111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 22, 9, 20, 36, 607111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_invoices', to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcations.Occupation', verbose_name='Απασχόληση'),
        ),
    ]
