# Generated by Django 2.0.5 on 2018-12-02 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0002_auto_20181202_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 2, 16, 54, 8, 816272, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
