# Generated by Django 2.0 on 2018-12-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0003_auto_20181202_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericexpense',
            options={'ordering': ['is_paid', '-date_expired'], 'verbose_name': 'Εντολή Πληρωμής', 'verbose_name_plural': '3. Εντολή Πληρωμής Γενικών Εξόδων'},
        ),
        migrations.AlterModelOptions(
            name='genericexpensecategory',
            options={'verbose_name': 'Έξοδο', 'verbose_name_plural': '7. Γενικά Έξοδα'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Απασχόληση', 'verbose_name_plural': '5. Απασχόληση'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['is_paid', '-date_expired'], 'verbose_name': 'Εντολή Πληρωμής', 'verbose_name_plural': '2. Μισθόδοσία'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='transcations.BillCategory', verbose_name='Λογαριασμός'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Επιπλέον Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμένο?'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='transcations.GenericExpenseCategory'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Επιπλέον Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμένο?'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Επιπλέον Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμένο?'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_invoices', to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transcations.Occupation', verbose_name='Απασχόληση'),
        ),
    ]
