# Generated by Django 2.0 on 2018-08-24 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0003_auto_20180822_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['is_paid', 'date_expired']},
        ),
        migrations.AlterModelOptions(
            name='genericexpense',
            options={'ordering': ['is_paid', 'date_expired']},
        ),
        migrations.AddField(
            model_name='billcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genericexpensecategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occupation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 24, 13, 4, 48, 735417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 24, 13, 4, 48, 735417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 24, 13, 4, 48, 735417, tzinfo=utc)),
        ),
    ]
