# Generated by Django 2.0.5 on 2018-08-28 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0004_auto_20180824_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date_expired']},
        ),
        migrations.AlterModelOptions(
            name='genericexpense',
            options={'ordering': ['is_paid', '-date_expired']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 19, 31, 42, 163296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='transcations.GenericExpenseCategory'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 19, 31, 42, 163296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 19, 31, 42, 163296, tzinfo=utc)),
        ),
    ]
