# Generated by Django 2.0.5 on 2018-08-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='categories',
            field=models.ManyToManyField(blank=True, to='frontend.CategorySite'),
        ),
    ]
