# Generated by Django 2.0.5 on 2018-08-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_coupons_categories'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
        migrations.AddField(
            model_name='cartrules',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='cartrules',
            name='coupons',
            field=models.ManyToManyField(to='carts.Coupons'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SizeAttribute'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='cartgiftitem',
            name='cart_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='cartgiftitem',
            name='product_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ManyToManyField(to='carts.Coupons'),
        ),
    ]
