# Generated by Django 2.0 on 2018-06-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180608_1813'),
        ('carts', '0002_cartgiftitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartgiftitem',
            unique_together={('cart_related', 'product_related')},
        ),
    ]
