# Generated by Django 2.0.5 on 2018-06-12 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180611_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartgiftitem',
            name='cart_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='carts.Cart'),
        ),
    ]
