# Generated by Django 2.0.5 on 2018-10-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20181004_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Value gets a priority vs percent. Period', max_digits=10, null=True),
        ),
    ]
