# Generated by Django 2.0 on 2018-06-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20180612_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='carts.Cart'),
        ),
    ]
