# Generated by Django 2.0.5 on 2018-10-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20181005_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='whole_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value gets a priority vs percent. Period', max_digits=10, verbose_name='Discount in Value'),
        ),
    ]
