# Generated by Django 2.0 on 2018-06-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20180612_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartgiftitem',
            unique_together=set(),
        ),
    ]
