# Generated by Django 2.0.5 on 2018-12-02 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('cellphone', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('costumer_submit', models.BooleanField(default=True, verbose_name='Are you sure?')),
            ],
        ),
        migrations.CreateModel(
            name='CostumerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('shipping_address_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Address')),
                ('shipping_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('shipping_zip_code', models.IntegerField(blank=True, null=True, verbose_name='Postal')),
                ('billing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_zip_code', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone')),
                ('phone1', models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='Cell Phone')),
                ('fax', models.CharField(blank=True, max_length=10, verbose_name='Fax')),
                ('is_retail', models.BooleanField(default=True)),
                ('is_eshop', models.BooleanField(default=True)),
                ('afm', models.CharField(blank=True, max_length=9, verbose_name='ΑΦΜ')),
                ('DOY', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Balance')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GuestEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
