# Generated by Django 2.0.5 on 2018-10-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20181005_0941'),
        ('accounts', '0002_auto_20181013_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='cellphone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='costumer_submit',
            field=models.BooleanField(default=True, verbose_name='Are you sure?'),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='first_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='last_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Country'),
        ),
    ]
