# Generated by Django 2.0.5 on 2018-12-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0001_initial'),
        ('accounts', '0002_auto_20181202_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Country'),
        ),
    ]
