# Generated by Django 2.0 on 2018-09-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180917_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumeraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='costumeraccount',
            name='last_name',
        ),
    ]
