# Generated by Django 2.0.5 on 2018-12-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='user',
        ),
    ]
