# Generated by Django 2.0.5 on 2018-10-15 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181014_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.AlterField(
            model_name='address',
            name='billing_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.BillingProfile'),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
