# Generated by Django 2.0 on 2018-10-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181015_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumeraccount',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='costumeraccount',
            name='last_name',
            field=models.CharField(blank=True, help_text='Only needed if not user related', max_length=150, null=True),
        ),
    ]
