# Generated by Django 2.0 on 2018-09-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_costumeraccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeraccount',
            name='name',
            field=models.CharField(blank=True, help_text='Only needed if not user related', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
