# Generated by Django 2.0 on 2018-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181016_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cell Phone'),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='shipping_address_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='shipping_zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Postal'),
        ),
    ]
