# Generated by Django 2.0.5 on 2018-06-01 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_site', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('1', 'Νέα Παραγγελία'), ('2', 'Σε Επεξεργασία'), ('3', 'Έτοιμο προς Αποστολή'), ('4', 'Απεστάλη'), ('5', 'Επιστράφηκε'), ('6', 'Ακυρώθηκε'), ('7', 'Εισπράκτηκε'), ('8', 'Ολοκληρώθηκε')], default='1', max_length=1)),
                ('order_type', models.CharField(choices=[('r', 'Λιανική Πώληση'), ('e', 'Eshop'), ('b', 'Επιστροφές'), ('d', 'Καταστροφή Προϊόντων'), ('wa', 'Παραστατικό Εισαγωγής'), ('wr', 'Παραστατικό Εξαγωγής')], default='r', max_length=1)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικό Κόστος Παραγγελίας')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('day_sent', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Έπίθετο')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Διεύθυνση')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Νομός')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ΤΚ')),
                ('cellphone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Κινητό')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Σταθερό Τηλεφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('costumer_submit', models.BooleanField(default=True, verbose_name='Επιβεβαίωση')),
                ('eshop_order_id', models.CharField(blank=True, max_length=10, null=True)),
                ('eshop_session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_related', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.Cart')),
                ('costumer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.CostumerAccount', verbose_name='Πελάτης')),
                ('coupons', models.ManyToManyField(to='carts.Coupons')),
                ('order_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.RetailOrder')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.Shipping')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Παραστατικά Πωλήσεων',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RetailOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price_discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_find', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.RetailOrder')),
            ],
            options={
                'verbose_name_plural': '2. Προϊόντα Πωληθέντα',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
