# Generated by Django 2.0.5 on 2018-12-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('point_of_sale', '0001_initial'),
        ('carts', '0002_auto_20181202_1511'),
        ('accounts', '0002_auto_20181202_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SizeAttribute'),
        ),
        migrations.AddField(
            model_name='retailorderitem',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='address_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Address'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='billing_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.BillingProfile'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='cart_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='costumer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CostumerAccount', verbose_name='Costumer'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='carts.Coupons'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='order_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.RetailOrder'),
        ),
    ]
