# Generated by Django 2.0.5 on 2018-06-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20180603_0934'),
        ('point_of_sale', '0002_retailorderitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentMethod'),
        ),
    ]
