# Generated by Django 2.0 on 2018-08-22 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_auto_20180821_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 22, 9, 20, 36, 607111, tzinfo=utc)),
        ),
    ]
