# Generated by Django 2.0.5 on 2018-06-04 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180601_0949'),
        ('point_of_sale', '0003_auto_20180603_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SizeAttribute'),
        ),
    ]
