# Generated by Django 2.0 on 2018-06-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_retailorderitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailorderitem',
            old_name='price',
            new_name='discount_value',
        ),
        migrations.RenameField(
            model_name='retailorderitem',
            old_name='price_discount',
            new_name='value',
        ),
    ]
