# Generated by Django 2.0 on 2018-06-06 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0005_auto_20180604_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='carts.Coupons'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
