# Generated by Django 2.0.5 on 2018-10-13 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181013_1751'),
        ('point_of_sale', '0005_auto_20181005_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='billing_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.BillingProfile'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='costumer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.CostumerAccount', verbose_name='Costumer'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 10, 13, 14, 51, 2, 130622, tzinfo=utc)),
        ),
    ]
