# Generated by Django 2.0.5 on 2018-06-07 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0006_auto_20180606_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='point_of_sale.RetailOrder'),
        ),
    ]
