# Generated by Django 2.0 on 2018-12-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0006_auto_20181212_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='order_type',
            field=models.CharField(choices=[('r', 'Λιανική Πώληση'), ('e', 'Πώληση Eshop'), ('b', 'Παραστατικό Επιστροφής'), ('c', 'Ακυρωμένη Παραγγελία'), ('wa', 'Παραστατικό Εισαγωγής'), ('wr', 'Παραστατικό Εξαγωγής')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='status',
            field=models.CharField(choices=[('1', 'Νέα Παραγγελία'), ('2', 'Σε επεξεργασία'), ('3', 'Έτοιμη προς αποστολή'), ('4', 'Απεστάλη'), ('5', 'Επιστράφηκε'), ('6', 'Ακυρώθηκε'), ('7', 'Εισπράκτηκε'), ('8', 'Ολοκληρώθηκε')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='retailorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='point_of_sale.RetailOrder'),
        ),
    ]
