# Generated by Django 2.0 on 2018-08-31 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0006_auto_20180828_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 31, 13, 12, 40, 733154, tzinfo=utc)),
        ),
    ]
