# Generated by Django 2.0.5 on 2018-12-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20181212_1428'),
        ('point_of_sale', '0007_auto_20181215_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailOrderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.PositiveIntegerField()),
                ('cellphone', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('order_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=1)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='retailorder',
            name='address_profile',
        ),
        migrations.RemoveField(
            model_name='retailorder',
            name='billing_profile',
        ),
        migrations.AddField(
            model_name='retailorderprofile',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='point_of_sale.RetailOrder'),
        ),
        migrations.AlterUniqueTogether(
            name='retailorderprofile',
            unique_together={('order_related', 'order_type')},
        ),
    ]
