# Generated by Django 2.0 on 2018-06-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180611_1628'),
        ('products', '0005_auto_20180608_1813'),
        ('point_of_sale', '0007_auto_20180607_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRetailItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('cart_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.CartItem')),
            ],
        ),
        migrations.AlterModelOptions(
            name='retailorder',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': '1. Παραστατικά Πωλήσεων'},
        ),
        migrations.AddField(
            model_name='giftretailitem',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.RetailOrder'),
        ),
        migrations.AddField(
            model_name='giftretailitem',
            name='product_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
