# Generated by Django 2.0 on 2018-09-17 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0008_auto_20180831_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 17, 15, 3, 51, 87341, tzinfo=utc)),
        ),
    ]
