# Generated by Django 2.0.5 on 2018-06-12 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0008_auto_20180611_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftretailitem',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='point_of_sale.RetailOrder'),
        ),
    ]
