# Generated by Django 2.0.5 on 2018-12-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0008_auto_20181216_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorderprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='retailorderprofile',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_profiles', to='point_of_sale.RetailOrder'),
        ),
    ]
