# Generated by Django 2.0 on 2018-10-17 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point_of_sale', '0009_auto_20181016_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='seller_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='costumer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CostumerAccount', verbose_name='Costumer'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 11, 2, 51, 725788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='status',
            field=models.CharField(choices=[('1', 'New Order'), ('2', 'In Progress'), ('3', 'Έτοιμο προς Αποστολή'), ('4', 'Απεστάλη'), ('5', 'Επιστράφηκε'), ('6', 'Ακυρώθηκε'), ('7', 'Εισπράκτηκε'), ('8', 'Ολοκληρώθηκε')], default='1', max_length=1),
        ),
    ]
