# Generated by Django 2.0.5 on 2018-12-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0009_auto_20181216_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorderprofile',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailorderprofile',
            name='cellphone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='retailorderprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retailorderprofile',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
