# Generated by Django 2.0 on 2018-06-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0009_auto_20180612_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftretailitem',
            name='cart_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.Cart'),
        ),
    ]
