# Generated by Django 2.0 on 2018-07-04 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0010_auto_20180612_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 7, 4, 12, 49, 59, 567445, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
