# Generated by Django 2.0 on 2019-01-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0010_auto_20181216_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailorder',
            options={'ordering': ['-date_expired'], 'verbose_name': 'Πώληση', 'verbose_name_plural': '1. Παραστατικά Πωλήσεων'},
        ),
        migrations.AlterField(
            model_name='retailorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='point_of_sale.RetailOrder'),
        ),
        migrations.AlterField(
            model_name='retailorderitem',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='retailorderprofile',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_profiles', to='point_of_sale.RetailOrder'),
        ),
        migrations.AlterField(
            model_name='retailorderprofile',
            name='order_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=50),
        ),
    ]
