# Generated by Django 2.0 on 2018-08-03 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0011_retailorder_date_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailorderitem',
            options={'ordering': ['-order__timestamp'], 'verbose_name_plural': '2. Προϊόντα Πωληθέντα'},
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 10, 15, 36, 629762, tzinfo=utc)),
        ),
    ]
