# Generated by Django 2.0.5 on 2018-09-26 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_auto_20180917_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 4, 32, 58, 865767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='order_type',
            field=models.CharField(choices=[('r', 'Retail Order'), ('e', 'Eshop'), ('b', 'Return Order'), ('wa', 'Παραστατικό Εισαγωγής'), ('wr', 'Export Invoice')], default='r', max_length=1),
        ),
    ]
