# Generated by Django 2.0 on 2018-08-03 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_auto_20180803_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorderitem',
            name='total_cost_value',
            field=models.DecimalField(decimal_places=0, default=0, help_text='qty*cost', max_digits=20),
        ),
        migrations.AddField(
            model_name='retailorderitem',
            name='total_value',
            field=models.DecimalField(decimal_places=0, default=0, help_text='qty*final_value', max_digits=20),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 12, 35, 3, 890876, tzinfo=utc)),
        ),
    ]
