# Generated by Django 2.0.5 on 2018-09-27 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0018_auto_20180926_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 27, 5, 1, 55, 958282, tzinfo=utc)),
        ),
    ]
