# Generated by Django 2.0 on 2019-01-31 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysite',
            options={'verbose_name_plural': '3. Κατηγορίες Site'},
        ),
        migrations.AddField(
            model_name='categorysite',
            name='edited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categorysite',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorysite',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorysite',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorysite',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorysite',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorysite',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorysite',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='frontend.CategorySite'),
        ),
        migrations.AlterUniqueTogether(
            name='categorysite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='order',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='title',
        ),
    ]
