# Generated by Django 2.0.5 on 2018-06-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentorders',
            old_name='payment_type',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='paymentorders',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='paymentorders',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
