# Generated by Django 2.0 on 2018-10-04 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='first_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping',
            name='first_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 10, 4, 12, 36, 47, 967812, tzinfo=utc)),
        ),
    ]
