# Generated by Django 2.0 on 2018-12-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20181202_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Επιπλέον Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='paymentorders',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμένο?'),
        ),
        migrations.AlterField(
            model_name='paymentorders',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
    ]
