# Generated by Django 2.0 on 2019-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20181212_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
