# Generated by Django 2.0.5 on 2018-08-28 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20180824_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorders',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 19, 31, 42, 163296, tzinfo=utc)),
        ),
    ]
