# Generated by Django 2.0.5 on 2018-10-14 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20181013_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 10, 14, 6, 54, 40, 124671, tzinfo=utc)),
        ),
    ]
