# Generated by Django 2.0 on 2019-01-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20190130_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
    ]
