# Generated by Django 2.0.5 on 2019-02-01 07:32

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_auto_20190131_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name_plural': 'Τρόποι Πληρωμής'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['-ordering_by'], 'verbose_name_plural': 'Τρόποι Μεταφοράς'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': 'Κατάστημα'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Επιπλέον Κόστος'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='limit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Όριο'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='site_active',
            field=models.BooleanField(default=False, verbose_name='Εμφάνιση στο site'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[site_settings.models.validate_positive_decimal], verbose_name='Κόστος'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='first_choice',
            field=models.BooleanField(default=False, verbose_name='Πρώτη Επιλόγη'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='limit_value',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6, validators=[site_settings.models.validate_positive_decimal], verbose_name='Όριο'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='ordering_by',
            field=models.IntegerField(default=1, verbose_name='Σειρα Προτεριότητας'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Τίτλος'),
        ),
    ]
