# Generated by Django 2.0 on 2018-09-17 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_auto_20180917_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 17, 16, 8, 20, 676669, tzinfo=utc)),
        ),
    ]
