# Generated by Django 2.0.5 on 2018-09-26 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_auto_20180917_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 4, 32, 58, 865767, tzinfo=utc)),
        ),
    ]
