# Generated by Django 2.0.5 on 2018-09-26 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_auto_20180926_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 5, 0, 33, 721912, tzinfo=utc)),
        ),
    ]
