# Generated by Django 2.0 on 2018-09-28 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0018_auto_20180927_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 28, 5, 50, 1, 709638, tzinfo=utc)),
        ),
    ]
