# Generated by Django 2.0.5 on 2018-06-01 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import my_site.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ενεργοποίηση')),
                ('title', models.CharField(max_length=120, verbose_name='Ονομασία Brand')),
                ('image', models.ImageField(blank=True, upload_to='brands/', verbose_name='Εικόνα')),
                ('order_by', models.IntegerField(default=1, verbose_name='Σειρά Προτεριότητας')),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('width', models.IntegerField(default=240)),
                ('height', models.IntegerField(default=240)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Brands',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='CategorySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, help_text='610*410', null=True, upload_to=my_site.models.category_site_directory_path)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=1)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('show_on_menu', models.BooleanField(default=False, verbose_name='Active on Navbar')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='my_site.CategorySite')),
            ],
            options={
                'verbose_name_plural': '3. Κατηγορίες Site',
                'ordering': ['-order'],
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[my_site.models.validate_positive_decimal])),
                ('active_cost', models.BooleanField(default=True)),
                ('active_minimum_cost', models.DecimalField(decimal_places=2, default=40, max_digits=6, validators=[my_site.models.validate_positive_decimal])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings.Country')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='categorysite',
            unique_together={('slug', 'parent')},
        ),
    ]
