# Generated by Django 2.0.3 on 2018-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_auto_20180605_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['ordering_by']},
        ),
        migrations.AddField(
            model_name='shipping',
            name='ordering_by',
            field=models.IntegerField(default=1),
        ),
    ]
