# Generated by Django 2.0 on 2018-06-05 11:06

from django.db import migrations, models
import my_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20180605_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=my_site.models.upload_banner, validators=[my_site.models.validate_size])),
                ('href', models.URLField(blank=True, null=True)),
                ('new_window', models.BooleanField(default=False)),
                ('big_banner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to=my_site.models.upload_location, validators=[my_site.models.validate_size])),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.CharField(max_length=160)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['-ordering_by']},
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='active_cost',
        ),
    ]
