# Generated by Django 2.0 on 2018-08-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_auto_20180605_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysite',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='my_site.CategorySite'),
        ),
    ]
