# Generated by Django 2.0 on 2018-10-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('inventory_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsize',
            name='product_attr_related',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SizeAttribute'),
        ),
        migrations.AddField(
            model_name='orderitemsize',
            name='size_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Size'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory_manager.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Προϊόν'),
        ),
    ]
