# Generated by Django 2.0.5 on 2019-02-07 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_manager', '0001_initial'),
        ('site_settings', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
        migrations.AddField(
            model_name='orderitemsize',
            name='order_item_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='inventory_manager.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitemsize',
            name='product_attr_related',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SizeAttribute'),
        ),
        migrations.AddField(
            model_name='orderitemsize',
            name='size_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Size'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory_manager.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='products.Product', verbose_name='Προϊόν'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='inventory_manager.Vendor', verbose_name='Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('product', 'order_related')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitemsize',
            unique_together={('order_item_related', 'size_related')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
