# Generated by Django 2.0 on 2018-06-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0002_order_orderitem_preorder_warehouseorderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='final_price',
        ),
    ]
