# Generated by Django 2.0.5 on 2018-12-02 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0003_auto_20181202_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
