# Generated by Django 2.0 on 2018-10-04 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0003_auto_20181004_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 10, 4, 12, 36, 47, 967812, tzinfo=utc)),
        ),
    ]
