# Generated by Django 2.0 on 2018-06-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0003_auto_20180628_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('1', 'Τιμολόγιο - Δελτίο Αποστολής'), ('2', 'Τιμολόγιο'), ('3', 'Δελτίο Απόστολης'), ('4', 'Εισαγωγή Αποθήκης'), ('5', 'Εξαγωγή Αποθήκης')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_no_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Καθαρή Αξία'),
        ),
    ]
