# Generated by Django 2.0 on 2018-12-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory_manager', '0004_auto_20181202_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['product'], 'verbose_name': 'Συστατικά Τιμολογίου'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price_no_discount',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Επιπλέον Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμένο?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Συνολική Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Καθαρή Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Συνολικοί Φόροι'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ποσοστό Έκτωσης'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Τελευταίας Επεξεργασίας'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Αξία'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='taxes',
            field=models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='3', max_length=1, verbose_name='ΦΠΑ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('1', 'Τεμάχια'), ('2', 'Κιλά'), ('3', 'Κιβώτια')], default='1', max_length=1, verbose_name='Μονάδα Μέτρησης'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Άρχικη Αξία'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
