# Generated by Django 2.0 on 2018-08-20 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0004_auto_20180820_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 15, 5, 44, 861655, tzinfo=utc)),
        ),
    ]
