# Generated by Django 2.0 on 2018-08-24 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0005_auto_20180822_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 8, 24, 13, 4, 48, 735417, tzinfo=utc)),
        ),
    ]
