# Generated by Django 2.0 on 2018-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0005_auto_20180628_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='taxes_modifier',
            field=models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='taxes',
            field=models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='taxes_modifier',
            field=models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='3', max_length=1),
        ),
    ]
