# Generated by Django 2.0 on 2018-08-03 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0006_auto_20180630_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 10, 15, 36, 629762, tzinfo=utc)),
        ),
    ]
