# Generated by Django 2.0 on 2019-01-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0006_auto_20181212_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
