# Generated by Django 2.0 on 2018-08-03 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0007_auto_20180803_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 12, 35, 3, 890876, tzinfo=utc)),
        ),
    ]
