# Generated by Django 2.0 on 2018-10-17 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0010_auto_20181016_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 11, 2, 51, 725788, tzinfo=utc)),
        ),
    ]
