# Generated by Django 2.0.5 on 2018-09-26 04:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory_manager', '0013_auto_20180917_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('attr_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SizeAttribute')),
                ('order_item_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='inventory_manager.OrderItem')),
                ('product_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 4, 32, 58, 865767, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='orderitemattribute',
            unique_together={('product_related', 'attr_related')},
        ),
    ]
