# Generated by Django 2.0.5 on 2018-09-26 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory_manager', '0018_auto_20180926_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('order_item_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='inventory_manager.OrderItem')),
                ('size_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Size')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderitemattribute',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitemattribute',
            name='order_item_related',
        ),
        migrations.RemoveField(
            model_name='orderitemattribute',
            name='size_related',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 5, 1, 10, 564333, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='OrderItemAttribute',
        ),
        migrations.AlterUniqueTogether(
            name='orderitemsize',
            unique_together={('order_item_related', 'size_related')},
        ),
    ]
