# Generated by Django 2.0.5 on 2018-09-27 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0019_auto_20180926_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 27, 5, 1, 55, 958282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitemsize',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
