# Generated by Django 2.0 on 2018-09-28 05:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory_manager', '0020_auto_20180927_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsize',
            name='product_attr_related',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SizeAttribute'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2018, 9, 28, 5, 50, 1, 709638, tzinfo=utc)),
        ),
    ]
