# Generated by Django 2.0 on 2018-12-12 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Color', verbose_name='Χρώμσ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=True, verbose_name='Προσφορά'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Υπηρεσία'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site_active',
            field=models.BooleanField(default=True, verbose_name='Ενεργό στο Site'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.BooleanField(default=False, verbose_name='Μεγεθολόγιο'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_active',
            field=models.BooleanField(default=False, verbose_name='Χονδρεμποριο'),
        ),
    ]
