# Generated by Django 2.0.5 on 2018-06-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180601_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('gift_message', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('product_related', models.ManyToManyField(related_name='product_related', to='products.Product')),
                ('products_gift', models.ManyToManyField(related_name='gifts', to='products.Product')),
            ],
        ),
    ]
