# Generated by Django 2.0 on 2018-06-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_gifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='products_gift',
            field=models.ManyToManyField(related_name='gifts_related', to='products.Product'),
        ),
    ]
