# Generated by Django 2.0 on 2018-06-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180608_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifts',
            name='products_gift',
        ),
        migrations.AddField(
            model_name='gifts',
            name='products_gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
