# Generated by Django 2.0 on 2019-01-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181215_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': '1. Προϊόντα'},
        ),
    ]
