# Generated by Django 2.0 on 2018-08-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180608_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': '1. Προϊόντα'},
        ),
        migrations.AlterModelOptions(
            name='productphotos',
            options={'ordering': ['is_primary'], 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['costum_ordering'], 'verbose_name_plural': '6. Μεγέθη'},
        ),
        migrations.AlterModelOptions(
            name='sizeattribute',
            options={'ordering': ['title'], 'verbose_name_plural': '2. Μεγεθολόγιο'},
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Product'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='sizeattribute',
            name='product_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='products.Product', verbose_name='Προϊόν'),
        ),
    ]
